name: Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/create-release@v1
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Actions build
          draft: true
          prerelease: false
    - name: Build on ${{ matrix.os }}
      run: cargo build --release
